project:
  type: website

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    html:
      raw: true

website:
  title: "DataFest 2025"
  sidebar:
    search: true
    logo: 'images/NU_Stat_logo.png'        
  navbar:
    collapse: true
    left:
      - href: signup.qmd
        text: Sign Up
      - href: schedule.qmd
        text: Schedule
      - href: panel_discussion.qmd
        text: Careers in Data Science
      - href: participants.qmd
        text: Participants
      - href: coc.qmd
        text: Rules & Code of Conduct
      - href: faqs.qmd
        text: FAQs
      - href: sponsors.qmd
        text: Sponsors
      - href: contactus.qmd
        text: Contact us
    
execute:
  freeze: auto

editor: source

