project:
  type: website

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    html:
      raw: true

website:
  title: "DataFest 2025"
  navbar:
    logo: 'images/NU_Stat_logo.png'    
    left:
      - href: signup.qmd
        text: Sign Up
      - href: schedule.qmd
        text: Schedule
      - href: coc.qmd
        text: Rules & Code of Conduct
      - href: faqs.qmd
        text: FAQs
    
execute:
  freeze: auto

editor: source

