project:
  type: website

website:
  title: "DataFest 2025"
  navbar:
    background: #4E2A84
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto

editor: source

