---
title: "FAQs"
format: html
---

## How do I sign up?

Register on the [sign-up](https://nustat.github.io/2026-datafest/signup.html) page.

## What do I bring to DataFest?

Please bring a laptop, charger and refillable water bottle.

## Is there a registration fee?

No, there is no registration fee. However note that the event takes significant resources to run. So, if you sign up, we expect that you will show up! If your plans change, let us know as soon as possible so we can make your spot available to someone else.

## Who is eligible to compete?

All undergraduate students at Northwestern University and University of Chicago are eligible.

## What about PhD and Masters students?

We would like to have Ph.D. and Masters students from both Northwestern and University of Chicago be involved as mentors during the event.

## How large are the teams?

Teams can be made up of 2 - 5 students.

## Do I have to compete in a team?

Yes, but if you don’t have a team in mind, select the “Looking for team” registration on the [Sign Up](https://nustat.github.io/2026-datafest/signup.html) page and we’ll match you with others looking for teammates.

## What do I need to compete?

All you need is a laptop with tools for data analysis *(there is no limitation on which software you use)* and enthusiasm for data.

## What are the rules of the competition?

Check the [rules](https://nustat.github.io/2026-datafest/coc.html) tab.

## How do I submit my analysis?

Once the registration window closes, participants will receive an email with a link to the project submission form.

## Where can I get help during the competition?

Mentors will be available in-person at venues of both Northwestern and University of Chicago on Saturday *(at times to be announced)* to answer questions.

## What can I win?

Winning teams will be awarded the ASA Student Membership along with other prizes.

## How many prizes are there?

There are four prizes - First, Second, Third, and People's Choice Award!

## Where else is ASA DataFest happening?

ASA DataFest is happening in several top universities around the world! See the list of all [participating institutions](https://ww2.amstat.org/education/datafest/participants.cfm).

## Are there any online resources that could be useful?

Yes, you may find the following resources useful:

### Data wrangling and visualization

* Data wrangling with Python: [https://nustat.github.io/DataScience_Intro_python/](https://nustat.github.io/DataScience_Intro_python/)

* Data wrangling with R: [https://r4ds.had.co.nz/](https://r4ds.had.co.nz/)

* Data visualization with R: [https://ggplot2-book.org/](https://ggplot2-book.org/)

### Interactive dashboard:
* Shiny
  + Deploy Shiny app on shinyapps.io: [https://docs.rstudio.com/shinyapps.io/getting-started.html](https://docs.rstudio.com/shinyapps.io/getting-started.html)
  + Shiny tutorials: [https://shiny.rstudio.com/tutorial/](https://shiny.rstudio.com/tutorial/)

* Tableau:
  + Tableau Public: [https://public.tableau.com/en-us/s](https://public.tableau.com/en-us/s)
  + Tableau Desktop - free student license: [https://www.tableau.com/academic](https://www.tableau.com/academic)
  
### Code repository, version control, and collaboration

* GitHub: [https://www.github.com](https://www.github.com)

* Happy Git with R: [https://happygitwithr.com/](https://happygitwithr.com/)