---
format: html
---

## Panel discussion session

There will be a panel discussion on **Careers in data science** on Sunday, 6th April from 5 to 6:30 pm at Guild Lounge. 

We are thrilled to introduce a diverse panel of [six experts](https://nustat.github.io/2025-datafest/panelists_judges.html), each with a distinct career path, yet all united by their connection to data science. Their journeys will illuminate the vast opportunities in the field, providing valuable insights into its complexities, work-life balance, and real-world impact. Don't miss this chance to learn from their experiences, ask questions, and grow your network!

## Networking with Capital One

Interested in connecting with [Capital One](https://www.capitalone.com/)? Capital one is the ninth largest bank in the United States by total assets as of 31st December 2024, the third largest issuer of Visa and Mastercard credit cards, and one of the largest car finance companies in the United States.

Capital One will be on campus Saturday, April 5th. During this time Capital One will be:

* hosting a resume review session

* discussing the Day in the Life of a Capital One associate, and

* talking about other networking opportunities

Be sure to attend to connect with Capital One and learn more about upcoming career opportunities! 

