## Schedule

Below is the tentative schedule for the event.

*Note: Students are encouraged to bring to-go boxes to take food home in case we have extra*

| Date | Time | Activity | Venue | 
|------|------|------|------|------|
| April 17th | 4:00 - 6:00 pm    | Social event    | Norris Louis room (Evanston)<sup>#</sup>    |
|---------------------------|-------------------------------------|------------------------------------------|-------------------------------------|
| April 24th | 5:30 - 6:30 pm    | Check-in \& Registration by    | Lutkin Hall (Evanston) / UChicago location*    |
| April 24th | 6:30 - 7:30 pm    |  Competition problem statement announcement  | Lutkin Hall (Evanston) / UChicago location*    |
| April 24th | 7:30 - 8:30 pm    | Fireside chat with Dr. Kaveh Safavi (Senior Executive Advisor, Accenture)    | Lutkin Hall (Evanston) / UChicago location*    |
| April 24th| 8:30 - 9:30 pm    | Meet \& Greet    | Lutkin Hall (Evanston) / UChicago location*    |
|---------------------------|-------------------------------------|------------------------------------------|-------------------------------------|
| April 25th | 10:30 - 11:00 am    | Check-in \& Breakfast    | Guild Lounge (Evanston) / UChicago location*    |
| April 25th | 11:00 am - 1:00 pm    | Student teams meet mentors, work on their solution    | Guild Lounge (Evanston) / UChicago location*    |
| April 25th | 1:00 - 2:00 pm    | Lunch    | Guild Lounge (Evanston) / UChicago location*    |
| April 25th | 2:00 - 6:00 pm    | Student teams working on their solution    | Guild Lounge (Evanston) / UChicago location*    |
|---------------------------|-------------------------------------|------------------------------------------|------------------------------------|
| April 26th | 10:00 - 11:45 am    | Check-in & wrap-up presentations     | Norris Louis Room (Evanston)**    | |
| April 26th | 11:45 - 12:45 pm    | Stop work \& lunch    | Norris Louis Room (Evanston)**    |
| April 26th | 12:45 - 1:00 pm    | Presentations preparation    | Norris Louis Room (Evanston)**    |
| April 26th | 1:00 - 4:30 pm    | Students presentations to judges    | Norris Louis Room (Evanston)**    |
| April 26th | 4:30 - 5:00 pm    | Break / setup for panel discussion    | Norris Louis Room (Evanston)**    |
| April 26th | 5:00 - 6:30 pm    | Panel discussion on *Careers in data science*    | Norris Louis Room (Evanston)**    |
| April 26th | 6:30 - 7:00 pm    | Awards    | Norris Louis Room (Evanston)**    |
| April 26th | 7:00 - 7:30 pm    | Extra time to accommodate any delay in schedule    | Norris Louis Room (Evanston)**    |


: Schedule {#tbl-letters}

<sup>#</sup>***April 17th (Friday):** Attendance in the in-person social event is optional. The event will include tips and tricks for the DataFest, conducted by faculty. 

\****April 24th & 25th (Friday & Saturday):** University of Chicago students can attend the event in-person either at UChicago (location within UChicago to be announced) or at Northwestern University. Northwestern University students are required to attend the event in Evanston.* 

\*\****April 26th (Sunday):** Students from both Northwestern University and the University of Chicago are required to attend the event in-person at Norris Louis Room in Evanston.*

*Mentors will be available to advise student teams at both the Universities at certain times of the day on April 25 (TBA)*

## Google map addresses

- Lutkin Hall, Evanston (April 24th 2026)

<div>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2962.634867007959!2d-87.68281992390659!3d42.05100947122322!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x880fd00b0c8664ef%3A0x1e4620e720a5313d!2sNorthwestern%20University%20-%20Lutkin%20Hall!5e0!3m2!1sen!2sus!4v1759713799245!5m2!1sen!2sus" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>

- Guild Lounge, Evanston (April 25th 2026)

<div>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2962.6090330457646!2d-87.68019482380144!3d42.05156335453571!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x880fd074ca661347%3A0xb3d0721c09135496!2sScott%20Hall!5e0!3m2!1sen!2sin!4v1735554008991!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>

- Location at University of Chicago on April 24th & 25th is to-be-announced.

-	Louis Room, Norris University Center, Evanston (April 26th)

<div>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2962.523439210994!2d-87.67524292380136!3d42.05339845442033!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x880fd07674e1804b%3A0x43dbf223a0a83d6a!2sNorris%20University%20Center!5e0!3m2!1sen!2sin!4v1735554454914!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>