---
title: "Sign Up!"
format: html
---

Each individual or team participating in the ASA DataFest at Northwestern University must submit a registration form. Everyone affiliated with **Northwestern University** and **University of Chicago** is invited to register with the relevant registration form.

* UG students are invited to register as participant, organizer, or volunteer.

* Graduate students, faculty, and industry professionals are invited to register as mentors, and / or organizers.

:::{.callout-note}

**Registration is open (to waitlist)!**

:::

## Participants 

**Want to compete in a data analysis competition, talk to data science professionals, and network?** Northwestern & University of Chicago undergraduate students are invited to register for the ASA DataFest 2026 at Northwestern University. If you form your own team, you will need to include information about each member of your team, including the team name. If you have not formed a team, you will have the chance on the registration form to request placement on a team. 

[Participant registration](https://northwestern.az1.qualtrics.com/jfe/form/SV_eFprY14OlSYXEiy)


## Mentors

**Want to mentor undergraduate student teams to help unleash their potential in the competition?** While graduate students and faculty cannot compete in the ASA DataFest at Northwestern University, we strongly encourage them to advise undergraduate student teams as mentors during the event! Please complete the Mentor sign-up form below.

[Mentor registration](https://northwestern.az1.qualtrics.com/jfe/form/SV_5bCCgs2YSyBoxBY)

## Organizing team

**Want to be a part of important decision-making & execution**, and help us organize the DataFest? Be an organizing committee member. You may join any of the following teams - (1) Publicity, (2) Logistics, (3) Communications, (4) Event coordination and planning. Please complete the organizing committee application below, and we'll get back soon!

[Organizing Committee member registration](https://northwestern.az1.qualtrics.com/jfe/form/SV_9HWC77bdkMVRR5k)

## Volunteers

**Want to be part of the fun without having to compete?** Be an event volunteer & help us run the event! There are several ways you can help - technical support, photography, social media, check-in desk, clean-up crew, etc. Join us during the event days (24th - 26th April 2026), hang out, meet people, and have food & fun! Please complete the volunteer sign-up form below.

[Event-day volunteer registration](https://northwestern.az1.qualtrics.com/jfe/form/SV_3KJGWIFl6CNeUrY)


:::{.callout-note}

If you have any questions about your registration, or about the DataFest, please contact Krish at krish [at] northwestern.edu
